// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mockdata.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import fakedata.actions.GenerateRandomString;
import mockdata.proxies.Accountants;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GenerateAccountants extends CustomJavaAction<IMendixObject>
{
	public GenerateAccountants(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMendixObject object = Core.instantiate(getContext(), Accountants.getType());

		object.setValue(getContext(), Accountants.MemberNames.Name.toString(),
				new GenerateRandomString(getContext(), "Accountants-??-######", true).execute());

		return object;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateAccountants";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
